test dont allow commit in main

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,2 +1,9 @@
 #!/usr/bin/env sh
+branch=$(git rev-parse --abbrev-ref HEAD)
+
+if [ "$branch" = "main" ]; then
+  echo "You cannot commit directly to main. Please create a feature branch."
+  exit 1
+fi
+
 npx lint-staged
